# docker-compose.yml
version: "3.9"

services:
  print-relay:
    build: .
    restart: unless-stopped
    # devices:
      # - "/dev/usb/lp0:/dev/usb/lp0"
    env_file:
      - .env
    environment:
      LOG_LEVEL: "info"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
